### ISSUE TITLE
不支持visual studio 2015 update2

### ISSUE THREAD

**Issue by fuchanghao** [Tsuki/VapourSynth-VSFilterMod#29]
会报错如下：

未定义标识符 "_mm_empty"  subtitles   d:\Source code\VapourSynth-VSFilterMod\src\subtitles\Rasterizer.cpp 1093    Intellisense

**Comment by Tsuki** [comment]
Hi fuchanghao,

Aleady open issue to MSDN.

please have a look on [this](https://social.msdn.microsoft.com/Forums/en-US/4774780d-bbc1-48f9-9604-e535d72228e5/mmempty-no-looker-work-in-visual-studio-2015-update2?forum=vcgeneral)

**Comment by Tsuki** [comment]
for workaround please use win32 build it.

**Comment by Tsuki** [comment]
for workaround please modify 

`c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\mmintrin.h`
- line 47:  `--#if defined(_M_IX86)`
- line 47:  `++#if defined(_M_IX86) || defined(_M_X64)`

**Comment by fuchanghao** [comment]
感谢，已编译成功。
